---
- hosts: webservers 
  become: True
  become_user: revo
  tasks:
    - name: Install packages
      apt:
        name: "nginx"
        state: "present"
    - name: Start Apache server
      service:
        name: nginx
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /home/revo
        
    
    
...
